Update calibration image to v1.15.1-rc2 (#72)

diff --git a/tools/calibration/Dockerfile b/tools/calibration/Dockerfile
--- a/tools/calibration/Dockerfile
+++ b/tools/calibration/Dockerfile
@@ -1,14 +1,19 @@
 # Create builder container
 FROM golang:1.17 as builder
 
+# Configure token for reading private repos
+ARG TOKEN
+ENV GOPRIVATE=github.com/Zondax/*
+RUN echo "machine github.com login $TOKEN password x-oauth-basic" > ~/.netrc
+
 # set BRANCH_FIL or COMMIT_HASH_FIL
-ARG BRANCH_FIL="v1.14.1"
+ARG BRANCH_FIL="v1.15.1-rc2"
 ARG COMMIT_HASH_FIL=""
 ARG REPO_FIL=https://github.com/filecoin-project/lotus
 ARG NODEPATH=/lotus
 
 # set BRANCH_PROXY or COMMIT_HASH_PROXY
-ARG BRANCH_PROXY=v1.1200.1
+ARG BRANCH_PROXY=v1.1402.1
 ARG COMMIT_HASH_PROXY=""
 ARG REPO_PROXY=https://github.com/Zondax/filecoin-indexing-rosetta-proxy.git
 ARG PROXYPATH=/rosetta-proxy
@@ -19,6 +24,32 @@ ENV DEBIAN_FRONTEND=noninteractive
 RUN apt-get update && \
     apt-get install -yy apt-utils && \
     apt-get install -yy gcc git bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev
+
+# Clone filecoin-indexing-rosetta-proxy
+RUN if [ -z "${BRANCH_PROXY}" ] && [ -z "${COMMIT_HASH_PROXY}" ]; then \
+  		echo 'Error: Both BRANCH_PROXY and COMMIT_HASH_PROXY are empty'; \
+  		exit 1; \
+    fi
+
+RUN if [ ! -z "${BRANCH_PROXY}" ] && [ ! -z "${COMMIT_HASH_PROXY}" ]; then \
+		echo 'Error: Both BRANCH_PROXY and COMMIT_HASH_PROXY are set'; \
+		exit 1; \
+	fi
+
+WORKDIR ${PROXYPATH}
+RUN git clone --recurse-submodules ${REPO_PROXY} ${PROXYPATH}
+
+RUN if [ ! -z "${BRANCH_PROXY}" ]; then \
+        echo "Checking out to proxy branch: ${BRANCH_PROXY}"; \
+  		git checkout ${BRANCH_PROXY}; \
+    fi
+
+RUN if [ ! -z "${COMMIT_HASH_PROXY}" ]; then \
+		echo "Checking out to proxy commit: ${COMMIT_HASH_PROXY}"; \
+		git checkout ${COMMIT_HASH_PROXY}; \
+	fi
+
+RUN make build
 
 # Clone Lotus
 RUN if [ -z "${BRANCH_FIL}" ] && [ -z "${COMMIT_HASH_FIL}" ]; then \
@@ -48,7 +79,7 @@ RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
 ENV PATH="/root/.cargo/bin:${PATH}"
 
 ENV RUSTFLAGS="-C target-cpu=native -g"
-ENV FFI_BUILD_FROM_SOURCE=1
+#ENV FFI_BUILD_FROM_SOURCE=1
 ARG DISABLE_SYNC
 
 # This will disable sync by setting the number of sync workers to 0
@@ -60,32 +91,6 @@ RUN if [ ! -z $DISABLE_SYNC ]; then \
 
 RUN make calibnet && make install
 
-
-# Clone filecoin-indexing-rosetta-proxy
-RUN if [ -z "${BRANCH_PROXY}" ] && [ -z "${COMMIT_HASH_PROXY}" ]; then \
-  		echo 'Error: Both BRANCH_PROXY and COMMIT_HASH_PROXY are empty'; \
-  		exit 1; \
-    fi
-
-RUN if [ ! -z "${BRANCH_PROXY}" ] && [ ! -z "${COMMIT_HASH_PROXY}" ]; then \
-		echo 'Error: Both BRANCH_PROXY and COMMIT_HASH_PROXY are set'; \
-		exit 1; \
-	fi
-
-WORKDIR ${PROXYPATH}
-RUN git clone --recurse-submodules ${REPO_PROXY} ${PROXYPATH}
-
-RUN if [ ! -z "${BRANCH_PROXY}" ]; then \
-        echo "Checking out to proxy branch: ${BRANCH_PROXY}"; \
-  		git checkout ${BRANCH_PROXY}; \
-    fi
-
-RUN if [ ! -z "${COMMIT_HASH_PROXY}" ]; then \
-		echo "Checking out to proxy commit: ${COMMIT_HASH_PROXY}"; \
-		git checkout ${COMMIT_HASH_PROXY}; \
-	fi
-
-RUN make build
 
 # Create final container
 FROM ubuntu:20.04
@@ -127,6 +132,9 @@ COPY --from=builder ${PROXYPATH}/filecoin-indexing-rosetta-proxy /usr/local/bin
 
 ENV LOTUS_RPC_URL=ws://127.0.0.1:1234/rpc/v0
 ENV LOTUS_RPC_TOKEN=""
+
+# Enable using WASM-compiled builtin actors
+ENV LOTUS_USE_FVM_EXPERIMENTAL=1
 
 EXPOSE $ROSETTA_PORT
 EXPOSE $LOTUS_API_PORT
